# -*- coding: utf-8 -*-
"""pb_request.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193hG5-wmcXgddkmxmv5EXZcWc8JhWx__
"""

#Laboratorio 04
#1. Inicializar un repositorio, configurar user.name/user.email...

mkdir laboratorio-git
cd laboratorio-git

git init

git config --global user.name "Beatjass"
git config --global user.email "jassiel.mejia@outlook.com"


#… y hacer 5 commits con Conventional Commits.
#Commit 1
echo "#Laboratorio 04" > README.md
git add README.md
git commit -m "chore: iniciar estructura base del repositorio"

#Commit 2
echo "Este repositorio contiene las actividades del laboratorio 04" >> README.md
git add README.md
git commit -m "docs: agregar archivo y descripción general en README"

#Commit 3
touch main.py
git add main.py
git commit -m "feat: añadir archivo de script principal"

#Commit 4 (fix)
echo "#Corrección de parametros" >> main.py
git add main.py
git commit -m "fix: corregir parametros en el script principal"

#Commit 5
echo "#Colaboración en github" >> colaboradores.md
git add colaboradores.md
git commit -m "chore: añadir al Dr. David como colaborador"

git log –oneline


#Escribir un .gitignore adecuado (datos, entornos, basura de herramientas)...
touch datos_prueba.log

git add datos_prueba.log
git commit -m "chore: añadir archivo de logs por error"

echo "*.log" > .gitignore

#… y demostrar con git rm --cached cómo se saca un archivo que ya estaba rastreado
git rm --cached datos_prueba.log

git add .gitignore
git commit -m "chore: ignorar archivos log y remover del rastreo"

#Enlace de mi repositorio: git remote add origin https://github.com/Beatjass/lab04.git

git branch -M main
git remote add origin https://github.com/Beatjass/lab04.git

git push -u origin main

#4. Crear una rama por issue y abrir un draft PR desde el primer commit de cada una
#Creé los issues en github

#Branch 1
git fetch origin
git checkout 1-feat-añadir-branch-de-prueba
echo "#Notas de branch de prueba" >> README.md

git add README.md
git commit -m "feat: iniciar desarrollo de rama de pruebas"

git push -u origin 1-feat-añadir-branch-de-prueba

#Branch 2
git fetch origin
git checkout 2-fix-configurar-exclusiones
echo "#Archivos ignorados" >> .gitignore

git add .gitignore
git commit -m "fix: configurar exclusiones de archivos DS_store"

git push -u origin 2-fix-configurar-exclusiones
#Tuve un error y subí el mismo commit dos veces

#5. Al terminar una rama: marcar el PR como ready for review y cerrar el issue con fixes #N en el mensaje
#Lo hice en github



#6. Provocar deliberadamente un conflicto de merge entre dos ramas y resolverlo
git checkout -b rama-A
echo "print('Trabajando en rama A')" > main.py
git add main.py
git commit -m "feat: modificar trabajo en rama A"

git checkout main
echo "print('Trabajando en la rama principal')" > main.py
git add main.py
git commit -m "feat: modificar trabajo en rama principal"


git merge rama-A
#Corregí el archivo main.py manualmente en la terminal y con nano
nano main.py
<<<<<<< HEAD
print('Trabajando en la rama principal')
=======
print('Trabajando en rama A')
>>>>>>> rama-A

git add main.py
git commit -m "fix: resolver conflicto de merge en main.py"


#7.1 Proteger main: requerir PR, ≥1 aprobación y CI en verde.
#Lo hice en github


#7.2 Comprobar que el push directo rebota
git checkout main
echo "#Prueba de bloqueo" >> README.md
git add README.md
git commit -m "chore: intento de push directo prohibido"
git push origin main

#Esto fue lo que me arrojo la terminal
#remote: Bypassed rule violations for refs/heads/main:
#remote:
#remote: - Changes must be made through a pull request.
#remote:

#8. Hacer fork del repositorio de un compañero y abrirle un PR; revisar el PR que te abran con ≥2 comentarios y al menos una suggestion aplicable.
#No la hice

#9. Agregar un workflow de GitHub Actions que corra ruff y pytest en cada push

mkdir -p .github/workflows
nano .github/workflows/ci.yml

#En nano
name: CI Quality Checks

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar versión de Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest

    - name: Ejecutar Linter (Ruff)
      run: |
        ruff check .

    - name: Ejecutar Pruebas Unitarias (Pytest)
      run: |
	pytest

#Archivo de prueba
echo "def test_ejemplo():\n    assert 1 + 1 == 2" > test_main.py

#git add .github/workflows/ci.yml test_main.py
#git commit -m "ci: agregar workflow de GitHub Actions para ruff y pytest"
#git push origin main
#Tuve un error con la sintaxis


#Crear el archivo test_main.py bien formateado
printf "def test_ejemplo():\n    assert 1 + 1 == 2\n" > test_main.py

#Hacer commit del archivo de prueba
git add test_main.py
git commit -m "test: agregar prueba unitaria valida para pytest"

git push origin main

#10. Recuperar con git reflog un commit borrado con reset –hard

echo "#Archivo a recuperar" > recuperar.txt
git add recuperar.txt
git commit -m "feat: agregar archivo para recuperar”
git reset --hard HEAD~1
git reflog

git log –oneline -n 3
ls recuperar.txt

#Entrega
git checkout -b entrega/lab04
git push -u origin entrega/lab04